### PR TITLE
Fixing the spGFN gradient

### PR DESCRIPTION
**Pull request by haneug**
Maybe a little primitive. I am open to suggestions.

### CODE REVIEW

**Comment by haneug** [comment]
I see I will have to update the test suite as well.

**Review by awvwgk — COMMENTED** [review]
I made a proposal to avoid the if condition in the spin loop. Please have a close look whether that works as expected.

**Comment by haneug** [comment]
Nice proposal! I had to make the spin iterator explicit after the do loop, else 'spin' will be larger 'nspin'. The results remain the same as with my initial commit.

**Review by awvwgk — APPROVED** [review]
Thanks for sharing looks good to me.

**Pull request merged**
